name: 04 - Understanding Runners (Win + Unbuntu)
on: push 
jobs:
    ubuntu-tunner:
        runs-on: ubuntu-latest
        steps:
            - name: Print Runner Details
              run: |
                echo "Workflow is executing on a Github-hosted runner."
                echo "Runner Name: $RUNNER_NAME"
                echo "Runner OS: $RUNNER_OS"
                echo "Runner Arcchitecture: $RUNNER_ARCH"
    windows-tunner:
        runs-on: windows-latest
        steps:
            - name: Print Runner Details
              shell: bash
              run: |
                echo "Workflow is executing on a Github-hosted runner."
                echo "Runner Name: $RUNNER_NAME"
                echo "Runner OS: $RUNNER_OS"
                echo "Runner Arcchitecture: $RUNNER_ARCH"